# Generated by Django 2.1.4 on 2018-12-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100, verbose_name='Data de Nasciemnto')),
                ('naturalidade', models.CharField(max_length=100, verbose_name='Naturalidade')),
                ('uf_nat', models.CharField(max_length=2, verbose_name='UF')),
                ('nome_pai', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=9, verbose_name='RG')),
                ('emissor', models.CharField(max_length=6)),
                ('dataexp', models.DateField(verbose_name='Data de Expedição')),
                ('uf', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
        ),
    ]
